apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: websecure
      port: 4443
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
