apiVersion: v1
kind: Service
metadata:
  namespace: devsu-python
  name: devsu-python-mcs
  labels:
    app: devsu-python-mcs
spec:
  ports:
    - protocol: TCP
      name: devsu-python-mcs
      port: 5000
  selector:
    app: devsu-python-mcs
