# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
name: "CI Pipeline"
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.3"]
    env:
      PORT: 5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Database setup
      - name: Set up database schema
        run: |
          python manage.py makemigrations
          python manage.py migrate
      # Run Tests
      - name: Run Tests
        run: python manage.py test
      # # Static code analisis
      # - name: Run Pysa Action
      #   uses: facebook/pysa-action
      #   with:
      #     repo-directory: './'
      #     requirements-path: 'requirements.txt'
      #     infer-types: true
      #     include-default-sapp-filters: true
      #     sapp-filters-directory: path/to/custom-filters
      # Code Coverage
      - name: Django Coverage action
        uses: actions/python-django-coverage-gitHub-action@0.9
        with:
          minimum-coverage: '80'
      # Docker image build & push  
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Git short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            -t danicaceres1998/devsu-python:${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
          docker push danicaceres1998/devsu-python --all-tags
