# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
name: "CI Pipeline"
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.3"]
    env:
      PORT: 5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Database setup
      - name: Set up database schema
        run: |
          python manage.py makemigrations
          python manage.py migrate
      # Run Tests
      - name: Run Tests
        run: python manage.py test
      # Docker image build & push  
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Git short sha
        id: git_context
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            -t danicaceres1998/devsu-python:${{ steps.git_context.outputs.branch }}-${{ steps.git_context.outputs.short_sha }}
          docker push danicaceres1998/devsu-python --all-tags
      # Snyk image scanner
      # - name: Run Snyk to check Docker image for vulnerabilities
      #   uses: snyk/actions/docker@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: danicaceres1998/devsu-python:${{ steps.git_context.outputs.branch }}-${{ steps.git_context.outputs.short_sha }}
